### ISSUE TITLE
connection geometric points (mid points) are not loaded 

### ISSUE THREAD

**Issue by apaikan** [robotology-playground/yarpmanager2#7]
Midpoints of connections are saved correctly to the file using builder: 

``` xml
<geometry>(Pos ((x -1) (y -1)) ((x 92) (y 80)) ((x 740.107) (y 368.266)) ((x 741.537) (y 495.55)) ((x 891.253) (y 495.133))  )</geometry>
```

![connection_points](https://cloud.githubusercontent.com/assets/4293456/13049107/eee85bc2-d3ea-11e5-8a81-7cf29ef87d79.png)

But they are ignored after loading the application:

![connection_mid2](https://cloud.githubusercontent.com/assets/4293456/13049123/0cbdd078-d3eb-11e5-9e61-45c29b360c25.png)

**Comment by aitek4iit** [comment]
Strange. Give a try after this commit.

**Comment by apaikan** [comment]
fixed!
