### ISSUE TITLE
manager crashes on refresh right after opening the application

### ISSUE THREAD

**Issue by apaikan** [robotology-playground/yarpmanager2#8]
- load an application in the manager
- click on the global refresh button 

crashes in `builderwindow.cpp:`

``` c++
void BuilderWindow::setOutputPortAvailable(QString oData, bool available)
{
    foreach (QGraphicsItem *it, scene->items()) {
        BuilderItem *item = (BuilderItem *)it;
==>        if(item->type() == QGraphicsItem::UserType + ModuleItemType){
...
```

**Comment by aitek4iit** [comment]
I can not reproduce it. Can you show me the application you are loading?

**Comment by apaikan** [comment]
I got the problem; an application crashes on refresh or select using mouse on the graphical view of the manager when there is a connection to a destination port object (maybe also for source port) with midpoints. see the bellow: 

![image](https://cloud.githubusercontent.com/assets/4293456/13568594/94aa4c50-e462-11e5-8309-dede65a5f727.png)
