### ISSUE TITLE
Yarpmanager crashes on connect from the graphical view

### ISSUE THREAD

**Issue by apaikan** [robotology-playground/yarpmanager2#9]
- load an application
- select a connection by clicking on the connection arrow from the graphic view
- right click to connect the ports
- it crashes in `builderwindow.cpp`: 

``` c++
void BuilderWindow::setOutputPortAvailable(QString oData, bool available)
{
    foreach (QGraphicsItem *it, scene->items()) {
        BuilderItem *item = (BuilderItem *)it;
        if(item->type() == QGraphicsItem::UserType + ModuleItemType){
...
```

**Comment by aitek4iit** [comment]
I can not reproduce it. Can you show me the application you are loading?

**Comment by apaikan** [comment]
@aitek4iit  This issue is also related to the problem of having connections with midpoints. See #8
